baseURL = 'https://theantichris.com/'
languageCode = 'en-us'
title = 'theantichris.com | christopher lamm'
theme = 'terminal'

[params]
 customCSS = ["css/custom.css"]

[params.logo]
logoText = 'theantichris.com'

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "resume"
url = "/resume/"
weight = 3

[markup.goldmark.renderer]
unsafe = true
